FROM docker.io/library/node:22-bookworm-slim

WORKDIR /app


COPY package*.json ./
RUN npm ci

COPY . .
RUN chmod +x ./container-entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["./container-entrypoint.sh"]
CMD ["npm", "start"]
